import React from "react";
import { Info } from "lucide-react";

/**
 * Disclaimer
 * Card #10 of the MarketGuard AI report — the final, compact section
 * stating the report's AI-generated, informational-only nature, followed
 * by a small muted footer credit. Static, no props required. Matches the
 * same design language as every other report card (white background,
 * rounded-xl border, subtle shadow, no animation).
 */
const Disclaimer = () => {
  return (
    <section className="w-full rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
      {/* ===================== CARD HEADER ===================== */}
      <h3 className="mb-2.5 text-xs font-bold uppercase tracking-wide text-slate-800">
        10. Disclaimer
      </h3>

      {/* ===================== DISCLAIMER CONTENT ===================== */}
      <div className="flex items-start gap-2.5">
        <Info className="mt-0.5 h-4 w-4 shrink-0 text-slate-400" strokeWidth={2} />
        <p className="text-[11px] leading-relaxed text-slate-500">
          This report is AI-generated using publicly available market data
          and is intended for educational and informational purposes only.
          It should not be considered financial or investment advice.
          Investors should conduct their own research before making
          investment decisions.
        </p>
      </div>

      {/* ===================== FOOTER ===================== */}
      <p className="mt-3 border-t border-slate-100 pt-2 text-center text-[10px] font-medium text-slate-400">
        Generated by MarketGuard AI
      </p>
    </section>
  );
};

export default Disclaimer;
