import React, { useMemo } from "react";
import { generateDocx } from "../../utils/docxGenerator";
// import { downloadPDF } from "../../utils/pdfGenerator";
import {
  ShieldCheck,
  CalendarDays,
  Clock,
  Hash,
  UserCog,
  Download,
  FileText,
  Share2,
} from "lucide-react";

/**
 * ReportHeader
 * Enterprise-grade report header for MarketGuard AI stock analysis reports.
 *
 * Props:
 * @param {Object} stock  - { company_name: string, current_price: number|string }
 * @param {string} symbol - Stock ticker symbol, e.g. "TCS"
 */
const ReportHeader = ({
  stock,
  symbol,
  reportData,
  onDownloadPDF,
}) => {
  const companyName = stock?.companyName || "Unknown Company";
  const tickerSymbol = stock?.symbol || symbol || "N/A";

  const now = useMemo(() => new Date(), []);

  const formattedDate = useMemo(
    () =>
      now.toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "2-digit",
      }),
    [now]
  );

  const formattedTime = useMemo(
    () =>
      now.toLocaleTimeString("en-US", {
        hour: "2-digit",
        minute: "2-digit",
        hour12: true,
      }),
    [now]
  );

  const reportId = useMemo(() => {
    const yy = String(now.getFullYear()).slice(-2);
    const mm = String(now.getMonth() + 1).padStart(2, "0");
    const dd = String(now.getDate()).padStart(2, "0");
    const symbolPart = (tickerSymbol || "NA").toString().toUpperCase();
    return `MGAI-${symbolPart}-${yy}${mm}${dd}-001`;
  }, [now, tickerSymbol]);

  const handleShare = async () => {
  const shareData = {
    title: "MarketGuard AI Report",
    text: `AI Stock Analysis Report - ${companyName} (${tickerSymbol})`,
    url: window.location.href,
  };

  try {
    if (navigator.share) {
      await navigator.share(shareData);
    } else {
      await navigator.clipboard.writeText(window.location.href);
      alert("Report link copied to clipboard!");
    }
  } catch (err) {
    console.error(err);
  }
};

const handleDownloadDocx = () => {
  console.table(reportData);
  generateDocx(reportData);
};



  return (
    <header className="w-full bg-white border border-slate-200 rounded-2xl shadow-sm px-5 py-6 sm:px-8 sm:py-8">
      {/* ===================== TOP SECTION ===================== */}
      <div className="flex flex-col gap-8 lg:flex-row lg:items-start lg:justify-between">
        {/* -------- LEFT: Brand -------- */}
        <div className="flex items-center gap-3 lg:flex-1">
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-blue-600 to-blue-700 shadow-sm">
            <ShieldCheck className="h-6 w-6 text-white" strokeWidth={2} />
          </div>
          <div>
            <h1 className="text-lg font-bold leading-tight tracking-tight text-slate-900 sm:text-xl">
              MarketGuard AI
            </h1>
            <p className="text-xs font-medium text-slate-500 sm:text-sm">
              AI-Powered Stock Intelligence
            </p>
          </div>
        </div>

        {/* -------- CENTER: Report Title -------- */}
        <div className="flex flex-col items-center text-center lg:flex-1">
          <span className="mb-1 inline-flex items-center rounded-full bg-blue-50 px-3 py-1 text-[10px] font-semibold uppercase tracking-widest text-blue-700 ring-1 ring-inset ring-blue-100">
            Equity Research
          </span>
          <h2 className="text-xl font-extrabold uppercase tracking-tight text-slate-900 sm:text-2xl">
            AI Stock Analysis Report
          </h2>
          <p className="mt-2 max-w-sm text-sm text-slate-500">
            Comprehensive AI-powered analysis of
            <br className="hidden sm:block" />{" "}
            <span className="font-semibold text-slate-700">
              {companyName}
            </span>{" "}
            <span className="font-mono text-slate-500">
              ({tickerSymbol})
            </span>
          </p>
        </div>

        {/* -------- RIGHT: Meta Info -------- */}
        <div className="grid grid-cols-2 gap-x-6 gap-y-3 rounded-xl bg-slate-50 p-4 text-xs sm:text-sm lg:flex lg:w-64 lg:flex-none lg:flex-col lg:gap-2 lg:bg-transparent lg:p-0 lg:text-right">
          <MetaRow
            icon={<UserCog className="h-4 w-4 text-slate-400" />}
            label="Generated By"
            value="MarketGuard AI"
          />
          <MetaRow
            icon={<CalendarDays className="h-4 w-4 text-slate-400" />}
            label="Date"
            value={formattedDate}
          />
          <MetaRow
            icon={<Clock className="h-4 w-4 text-slate-400" />}
            label="Time"
            value={formattedTime}
          />
          <MetaRow
            icon={<Hash className="h-4 w-4 text-slate-400" />}
            label="Report ID"
            value={reportId}
            mono
          />
        </div>
      </div>

      {/* ===================== DIVIDER ===================== */}
      <div className="my-6 h-px w-full bg-slate-100" />

      {/* ===================== ACTION BUTTONS ===================== */}
      <div className="flex flex-col-reverse gap-3 sm:flex-row sm:flex-wrap sm:justify-end">
        <button
        type="button"
        onClick={handleShare}
        className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:border-slate-300 hover:bg-slate-50 hover:shadow-md active:translate-y-0"
        >
          <Share2 className="h-4 w-4" />
          Share Report
        </button>

        <button
          type="button"
          onClick={handleDownloadDocx}
          className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:bg-emerald-700 hover:shadow-md active:translate-y-0"
        >
          <FileText className="h-4 w-4" />
          Download DOCX
        </button>

        <button
          type="button"
          onClick={onDownloadPDF}
          className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:bg-blue-700 hover:shadow-md active:translate-y-0"
        >
          <Download className="h-4 w-4" />
          Download PDF
        </button>
      </div>
    </header>
  );
};

/**
 * MetaRow - single label/value line used in the right-hand meta panel.
 */
const MetaRow = ({ icon, label, value, mono = false }) => (
  <div className="flex items-center gap-2 lg:justify-end">
    <span className="hidden lg:inline-flex">{icon}</span>
    <span className="text-slate-400">{label}:</span>
    <span
      className={`font-semibold text-slate-800 ${
        mono ? "font-mono tracking-tight" : ""
      }`}
    >
      {value}
    </span>
  </div>
);

export default ReportHeader;
